defaults:
  - _self_
  - algorithm: sprl
  - experiment/type: run
  - env: gate
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: colorlog

experiment:
  cores: 1
  mpi: 1
  log_rewards: false
  log_buffer: false
  amount: 1
  visualize: false

hydra:
  job:
    env_set:
      PYTHONWARNINGS: ignore